name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Install linters
        run: |
          pip install pytest black
      - name: Run black
        run: |
          black --check --diff .

  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.8, 3.9, 3.10]
    name: ${{ matrix.os }} Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install
        run: |
          pip install -r requirements.txt
          pip install -r requirements.test.txt

      - name: Test library
        run: |
          make test-coverage
          coverage xml

      - name: Test Docs
        run: |
          make test-docs
          cd doc
          make html
      
      - name: Upload coverage to codecov
        uses: actions/checkout@master
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

